wip
box/box-java-sdk pull request #1226
Opened 2024-01-12 12:46 UTC by lukaszsocha2

2024-01-12 18:06 UTC, jimshowalter requested changes

2024-01-12 18:06 UTC, jimshowalter commented on README.md
> +There are two ways of ensuring that decryption operation is FIPS compiant.
FIPS compiant -> FIPS-compliant

2024-01-12 18:06 UTC, jimshowalter commented on src/main/java/com/box/sdk/JWTEncryptionPreferences.java
> +     * Gets a decrytor used for decrypting the private key.
decrytor -> decryptor

2024-01-12 18:06 UTC, jimshowalter commented on src/test/java/com/box/sdk/BoxDeveloperEditionAPIConnectionTest.java
> +        String decryprtedPrivateKey = "MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC5fehGf7yDfLTDewsBcPyJSIIH1IB"
decryprtedPrivateKey - decryptedPrivateKey

2024-01-12 18:06 UTC, jimshowalter commented on src/test/java/com/box/sdk/BoxDeveloperEditionAPIConnectionTest.java
> +
Remove extra blank line.

2024-01-14 20:02 UTC, jimshowalter requested changes

2024-01-14 20:02 UTC, jimshowalter commented on README.md
> +which performs the decryption opertation using FIPS-certified library of your choice. The interface requires the
opertation -> operation

2024-01-14 20:02 UTC, jimshowalter commented on README.md
> +which performs the decryption opertation using FIPS-certified library of your choice. The interface requires the
privide -> provide

2024-01-14 20:03 UTC, jimshowalter requested changes

2024-01-14 20:03 UTC, jimshowalter commented on README.md
> +1. You can privide a custom implementation of the `IPrivateKeyDecryptor` interface,
privide -> provide

2024-01-15 10:56 UTC, lukaszsocha2 commented on src/test/java/com/box/sdk/BoxDeveloperEditionAPIConnectionTest.java
> +    @Test
I don't use and real decryptor in this test, so it doesn't matter what private key I use. I do't have monaco-crypto dependency here

2024-01-15 14:24 UTC, antusus approved these changes
👍

2024-01-16 14:28 UTC, merged